// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssgvhnqmlrrxnzatyzmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZ3ZobnFtbHJyeG56YXR5em1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTA5MzgsImV4cCI6MjA3MjMyNjkzOH0.uLp8cUNGfaW0GA5bHoAs2L6rPG8PoGkP9Thm38IbKcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});